name: Update Data Daily
on:
  schedule:
    - cron: "0,20,40 0-5 * * *" # Runs 20 min intervals converted to 12 AM to 5 AM UTC (7 PM to 1:30 AM ET)
  workflow_dispatch:  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run data update script
        env:
          YAHOO_ACCESS_TOKEN: ${{ secrets.YAHOO_ACCESS_TOKEN }}
          YAHOO_CONSUMER_KEY: ${{ secrets.YAHOO_CONSUMER_KEY }}
          YAHOO_CONSUMER_SECRET: ${{ secrets.YAHOO_CONSUMER_SECRET }}
          YAHOO_REFRESH_TOKEN: ${{ secrets.YAHOO_REFRESH_TOKEN }}
          YAHOO_TOKEN_TYPE: ${{ secrets.YAHOO_TOKEN_TYPE }}
          YAHOO_TOKEN_TIME: ${{ secrets.YAHOO_TOKEN_TIME }}
        run: |
          python FantasyApp.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "joeyounes2@gmail.com"
          git config --local user.name "jyoun110"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily data update" && git push)
