name: Update Data Daily
on:
  schedule:
    - cron: "30 7 * * *"  # Runs daily at 2:30 AM ET (7:30 AM UTC)
  workflow_dispatch:  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run data update script
        run: |
          python FantasyApp.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "joeyounes2@gmail.com"
          git config --local user.name "jyoun110"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily data update" && git push)
